Bug/windows devcontainer
uzh/pool pull request #122
Opened 2023-03-23 16:06 UTC by djust-uzh

This fixes the permission problems of the database folders from the devcontainer under Windows with Docker Desktop and wsl2 and adds the ability to optionally change devcontainer settings in the docker-compose.override.yml file. Also, apparently the `.env` file needs to be in the `.devcontainer/` folder in order to picket up by docker. So I moved the sample file there.

2023-03-28 06:43 UTC, timohuber requested changes
Thanks for the PR!

2023-03-28 06:43 UTC, timohuber commented on .devcontainer/docker-compose.yml
> +      - db-tenant:/dbs/db-tenant/:ro
Please use full name 
```suggestion
      - db-root:/databases/db-root/:ro
      - db-tenant:/databases/db-tenant/:ro
```

2023-03-28 06:43 UTC, timohuber commented on .devcontainer/.env.sample
Do you need to duplicate the `env.sample`? zsh should read the env file in the root directory.

2023-03-29 09:14 UTC, djust-uzh commented
This probably needs testing on macOS and linux. I currently don't have access to those platforms.

2023-03-29 09:50 UTC, timohuber commented on .devcontainer/.env.sample
We use `Zsh`. In the containers, the dotenv plugin is installed: https://github.com/uzh/pool/blob/main/.devcontainer/Dockerfile#L58

Currently there is a bug and Zsh is not used as the default terminal anymore. But if you open a new Zsh terminal inside the container, it should ask you if you want to update your environment. Does that work on your machine?

2023-03-29 09:51 UTC, timohuber commented
> This probably needs testing on macOS and linux. I currently don't have access to those platforms.

I did and it worked on my macOS.

2023-03-29 10:15 UTC, djust-uzh commented on .devcontainer/.env.sample
Yes it did work, but only after the installation in a new terminal. But the environment variable `ECON_PACKAGE_REGISTRY_READ_TOKEN` is already needed during installation. Otherwise the `scripts/setup.sh` fails during dependency installation. There is `opam init -a --shell=zsh` in `.devcontainer\postCreate.sh`, but this apparently does not automatically read the root `.env` file on my system. Only when I placed it into `.devcontainer` did the installation succeed.

2023-03-31 06:50 UTC, timohuber commented on .devcontainer/.env.sample
We all added the `ECON_PACKAGE_REGISTRY_READ_TOKEN` to our local zsh profiles. This gets mounted into the container. Could you please try that as well?
If it does not work, please remove all variables, except the `ECON_PACKAGE_REGISTRY_READ_TOKEN` from the `.devcontainer/.env.sample`. This is the only one needed there.

2023-04-06 09:06 UTC, mabiede commented on .devcontainer/devcontainer.json
@djust-uzh please move the `settings` and `extensions` section into `customizations/vscode` (latest update of the devcontainer.json specification)

here's the updated section:
```json
"customizations": {
    "vscode": {
      "settings": {
        "terminal.integrated.profiles.linux": {
          "zsh": {
            "path": "/bin/zsh"
          }
        },
        "terminal.integrated.defaultProfile.linux": "zsh",
        "editor.formatOnSave": true,
        "files.associations": {
          "*.ml": "ocaml",
          "*.mli": "ocaml"
        },
        "ocaml.sandbox": {
          "kind": "global",
        }
      },
      // Add the IDs of extensions you want installed when the container is created in the array below.
      "extensions": [
        "donjayamanne.githistory",
        "eamodio.gitlens",
        "exiasr.hadolint",
        "irongeek.vscode-env",
        "ocamllabs.ocaml-platform",
        "DavidAnson.vscode-markdownlint",
        "ms-vscode.makefile-tools"
      ]
    }
  }
```

2023-04-06 09:52 UTC, djust-uzh commented on .devcontainer/.env.sample
Since VSCode under Windows does not read any local bash or zsh profiles, I think the best solution is to set `ECON_PACKAGE_REGISTRY_READ_TOKEN` in `docker-compose.override.yml` and remove `.env.sample` alltogether. It still can be overridden by a local profile on supported platforms (linux and macOS). I did so with commit [097d906](https://github.com/uzh/pool/pull/122/commits/097d906cae5e08ba6a5a7d230e8a82b0ab31ce40).

2023-04-06 10:25 UTC, mabiede approved these changes

2023-04-11 09:09 UTC, merged