refactor session close view to store no shows
uzh/pool pull request #126
Opened 2023-03-30 11:45 UTC by timohuber

2023-04-04 14:40 UTC, mabiede requested changes

2023-04-04 14:40 UTC, mabiede commented on pool/app/pool_common/locales/i18n_en.ml
> +    {|S: the contact did not show up
Also `NS` like above?

```suggestion
    {|NS: the contact did not show up
```

2023-04-04 14:40 UTC, mabiede commented on pool/cqrs_command/assignment_command.ml
> +  let { num_show_ups; num_no_shows; num_participations; _ } = contact in
move to function header

```ocaml
({ Contact.num_show_ups; num_no_shows; num_participations; _ } as contact)
```

2023-04-14 11:17 UTC, timohuber commented on pool/app/pool_common/locales/i18n_en.ml
> +    {|S: the contact did not show up
Thanks for spotting that

2023-04-14 11:55 UTC, timohuber commented on pool/cqrs_command/assignment_command.ml
> +            | true, Some follow_ups ->
No, not without worsening readability. I cannot merge them in one boolean as I need to match with `follow_ups`.

2023-04-14 12:03 UTC, timohuber commented on pool/cqrs_command/assignment_command.ml
> +        (fun assignment -> MarkedAsDeleted assignment |> Pool_event.assignment)
Not it is

2023-04-14 12:09 UTC, timohuber commented on pool/web/handler/admin_experiments_assignments.ml
> +      match assignments with
No, this map is used to get the contact of the first assignment.

2023-04-20 12:29 UTC, mabiede commented on pool/database/migration/migration_202303291025.ml
> +      BEGIN NOT ATOMIC
@timohuber as discussed, split into separate steps.

2023-04-20 12:29 UTC, mabiede approved these changes

2023-04-21 09:37 UTC, merged