fix contact dashboard
uzh/pool pull request #149
Opened 2023-06-22 15:02 UTC by timohuber

2023-06-23 13:14 UTC, mabiede requested changes

2023-06-23 13:14 UTC, mabiede commented on pool/web/handler/contact_experiment.ml
> +       let _ =
debugging log or is this needed?

2023-06-26 05:27 UTC, timohuber commented on pool/web/handler/contact_experiment.ml
> +       let _ =
removed

2023-06-28 10:47 UTC, mabiede approved these changes

2023-06-28 12:16 UTC, merged