add reset invitations to experiment
uzh/pool pull request #222
Opened 2023-09-29 15:03 UTC by mabiede

- add reset invitations to experiment
- add resend count to invitations
- add optional mailing id to invitation
- hide update buttons on an experiment page for readers
- update base condition filter for matcher (resend invitations)

2023-10-11 06:15 UTC, timohuber requested changes
@mabiede 

- [x] Currently, resending invitations manually fails due to a SQL error
- [ ] What do you think of adding a statistics display on how many invitations have been sent N times and how many contacts have not been invited yet?

2023-10-16 08:26 UTC, mabiede commented on pool/app/filter/repo/repo_utils.ml
> +          AND pool_invitations.updated_at > ?
I'd instead implement it in the "distribution" section of a mailing (if this would be needed).

2023-10-16 08:27 UTC, mabiede commented on pool/app/invitation/repo/repo.ml
> +        LEFT JOIN pool_mailing
removed

2023-10-16 08:27 UTC, mabiede commented on pool/database/migration/migration_202309281435.ml
> +        ADD COLUMN resend_count integer NOT NULL DEFAULT 1 AFTER resent_at
True, renamed it to "send_count"

2023-10-16 08:30 UTC, mabiede commented
> * [ ]  What do you think of adding a statistics display on how many invitations have been sent N times and how many contacts have not been invited yet?

A short summary should show some information once the link between the invitation and mailing is possible/implemented.

2023-10-24 07:14 UTC, timohuber approved these changes

2023-10-24 07:14 UTC, merged