feat: Add Experiment Filters for Assignments and Invitations
uzh/pool pull request #258
Opened 2023-11-17 03:45 UTC by leostera

Still working here, opening to gather notes. So far:

- [x] New `hardcoded` field for Invitations
- [x] Adds a subquery for listing invitations
- [x] Creates a temporary table for Invitations
- [ ] Add support for Assignments
- [ ] Create integration test for different filters

2023-11-23 08:57 UTC, leostera commented on pool/app/experiment/entity.ml
> +let id t = t.id
Remove these.

2023-11-23 08:58 UTC, leostera commented on pool/app/filter/entity.ml
> +module Value = struct
Remove these.

2023-11-23 09:00 UTC, leostera commented on pool/app/filter/repo/repo.ml
> +    Format.fprintf
Remove these.

2023-11-23 09:01 UTC, leostera commented on pool/test/experiment_filter_test.ml
> +let ( let@ ) = Result.bind
Rename to `filter_invitation_test.ml`

2023-11-23 09:02 UTC, leostera commented on pool/test/assignments_filter_test.ml
> +(* test 1: 1 assigned contact, 1 probe contact test 2: 1 assigned contact marked
Move to next PR.

2023-11-23 11:33 UTC, leostera commented
@mabiede feel free to squash and remove some of the commit messages in the process :)

2023-11-23 12:05 UTC, mabiede requested changes
Nice, thanks. Added a few comments about left overs and adjustments to the consistency

2023-11-24 07:34 UTC, mabiede approved these changes

2023-11-24 13:48 UTC, merged