Feature/135 mail templates
uzh/pool pull request #66
Opened 2022-12-22 12:47 UTC by timohuber

2023-01-12 13:32 UTC, mabiede requested changes

2023-01-12 13:32 UTC, mabiede commented on pool/web/handler/contact_signup.ml
>               let open CCResult in
Open only the minimum
```suggestion
             let open CCResult.Infix in
```

2023-01-12 13:32 UTC, mabiede commented on pool/web/handler/contact_signup.ml
> +(* TODO: Make sure it works when logged in as well (PW update) *)
TODO: test/implement/follow-up issue

2023-01-12 13:32 UTC, mabiede commented on pool/web/handler/public_login.ml
> +    (* TODO: Make sure contact not found message is not displayed *)
TODO: test

2023-01-12 13:32 UTC, mabiede commented on pool/app/message_template/event.ml
> +  | Created template -> Repo.insert pool template
Add initialization of Guartian Authenticatable object (-> inserts target role to app and db)

2023-01-12 14:05 UTC, timohuber commented on pool/app/email/email.mli
> -  | Updated of
This event only creates the unverified email address in the database. The email, that is sent, is generated in the handlers and sent in the command.

2023-01-12 14:07 UTC, timohuber commented on pool/app/message_template/default/locales/default_de.ml
> +            "Du hast kürzlich eine neue E-Mail Adresse zu deinem Account \
As above

2023-01-12 14:16 UTC, timohuber commented on pool/app/email/event.ml
>    | EmailVerified of unverified t
Does not work because of `unverified t`

2023-01-12 14:18 UTC, timohuber commented on pool/app/message_template/message_template.ml
> +        ; text = "" (* TODO: Plaintext *)
305

2023-01-12 14:26 UTC, timohuber commented on pool/cqrs_command/invitation_command.ml
> +    let errors = CCList.map Contact.fullname errors in
Using Id

2023-01-12 14:28 UTC, timohuber commented on pool/cqrs_command/message_template_command.ml
> +    let* (_ : Pool_common.Language.t) =
Not sure if I understand your question. The language if `t` is the language selected in the message template form. `available_languages` are the tenant languages minus all languages of already created message templates.

2023-01-12 14:30 UTC, timohuber commented on pool/database/seed/seed_message_templates.ml
> +    DefaultRestored default_values_root |> handle_event Pool_database.root)
Yes, but on root, there is only PW reset.

2023-01-12 14:34 UTC, timohuber commented on pool/routes/routes.ml
> +      [ get "" new_get
Used "new_form" and "create", as it is a form to create a new template.

2023-01-12 14:36 UTC, timohuber commented on pool/routes/routes.ml
> +        [ get "edit" ~middlewares:[ Access.update ] edit
Does not make a difference

2023-01-12 14:38 UTC, timohuber commented on pool/web/handler/admin_session.ml
> +    |> database_label_of_req
No twice, see https://github.com/uzh/pool/pull/66/files#diff-94b92fe5e330c8177d75327a5c34c1824975583eb3d4cb4cdbd174304af07258R108

2023-01-12 14:43 UTC, timohuber commented on pool/web/handler/public_login.ml
> +    (* TODO: Make sure contact not found message is not displayed *)
Tested. It works as it should.

2023-01-12 15:08 UTC, timohuber commented on pool/web/handler/contact_signup.ml
> +(* TODO: Make sure it works when logged in as well (PW update) *)
Fixed it.

2023-01-12 15:48 UTC, timohuber commented on pool/web/handler/public_login.ml
> +  (* TODO: Make sure Token gets deactivated and correct error messages are
Fixed

2023-01-13 08:12 UTC, mabiede requested changes

2023-01-13 08:12 UTC, mabiede commented on pool/web/handler/admin_session.ml
> +    |> database_label_of_req
Use Infix operator `>==` without "lift"ing the result.

2023-01-13 08:12 UTC, mabiede commented on pool/web/handler/contact_signup.ml
> +(* TODO: Make sure it works when logged in as well (PW update) *)
remove todo

2023-01-13 08:12 UTC, mabiede commented on pool/web/handler/public_login.ml
> +  (* TODO: Make sure Token gets deactivated and correct error messages are
remove todo

2023-01-16 13:14 UTC, timohuber commented on pool/web/handler/admin_session.ml
> +    |> database_label_of_req
`req` is not an Lwt.t or a result, so you either use Lwt.return oder Lwt_result.lift.

2023-01-16 13:15 UTC, timohuber commented on pool/web/handler/contact_signup.ml
> +(* TODO: Make sure it works when logged in as well (PW update) *)
It is removed

2023-01-16 13:16 UTC, timohuber commented on pool/web/handler/public_login.ml
> +  (* TODO: Make sure Token gets deactivated and correct error messages are
It is removed

2023-01-16 13:16 UTC, timohuber commented on pool/app/email/entity.ml
> +type unverified = private XUnverifiedP [@@deriving eq, show]
removed

2023-01-16 14:34 UTC, mabiede approved these changes

2023-01-16 14:40 UTC, merged